name: apiverve_cpiinflation
description: CPI Inflation provides monthly Consumer Price Index data broken down by category including food, housing, transportation, medical care, and more. Includes year-over-year inflation rates for each category.
version: 1.1.14
homepage: https://apiverve.com/marketplace/cpiinflation?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/cpiinflation-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
